import type { Vixt } from '../vixt'

import fs from 'fs-extra'
import path from 'pathe'

export function generateAppConfig(vixt: Vixt) {
  const { buildImportsDir } = vixt.options
  let appConfigsImportTemplate = ''
  let appConfigsMergeTemplate = ''
  let i = 0
  for (const layer of vixt._layers) {
    const appConfigPath = path.resolve(layer.config!.srcDir!, 'app.config.ts')
    if (fs.existsSync(appConfigPath)) {
      const appConfigName = `__app_config_${i}`
      appConfigsImportTemplate += `import ${appConfigName} from '${appConfigPath}'\n`
      appConfigsMergeTemplate += `${appConfigName}, `
      i++
    }
  }

  const globalAppConfigKey = '__VIXT_APP_CONFIG'

  const appConfigTemplate = `
import { defu } from 'defu'
${appConfigsImportTemplate}
const appConfig = defu(${appConfigsMergeTemplate}{})
globalThis.${globalAppConfigKey} = appConfig
`
  // generate for auto-import
  fs.outputFileSync(path.resolve(buildImportsDir!, `app.config.ts`), `// Generated by Vixt
// @ts-nocheck
import type { VixtAppConfig } from '@vixt/core/client'

export const useAppConfig = () => globalThis.${globalAppConfigKey} as VixtAppConfig
`)
  return appConfigTemplate
}
