import type { Vixt } from '../vixt'

import fs from 'fs-extra'
import path from 'pathe'

export function generateClient(vixt: Vixt) {
  const { buildImportsDir } = vixt.options

  // generate for auto-import
  fs.outputFileSync(
    path.resolve(buildImportsDir!, `client.ts`),
    `// Generated by Vixt
export { defineAppConfig, defineVixtPlugin } from '@vixt/core/client'
`,
  )
}
