packages:
  - packages/*
  - playground/*
  - docs

catalog:
  '@antfu/eslint-config': ^4.13.2
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@dcloudio/types': ^3.4.15
  '@dcloudio/uni-app': 3.0.0-alpha-4060720250515001
  '@dcloudio/uni-app-plus': 3.0.0-alpha-4060720250515001
  '@dcloudio/uni-h5': 3.0.0-alpha-4060720250515001
  '@dcloudio/uni-mp-weixin': 3.0.0-alpha-4060720250515001
  '@dcloudio/uni-ui': ^1.5.7
  '@dcloudio/uni-uts-v1': 3.0.0-alpha-4060720250515001
  '@dcloudio/vite-plugin-uni': 3.0.0-alpha-4060720250515001
  '@iconify/react': ^6.0.0
  '@iconify/vue': ^5.0.0
  '@reactuses/core': ^6.0.2
  '@types/fs-extra': ^11.0.4
  '@types/react': ^19.1.5
  '@types/react-dom': ^19.1.5
  '@uni-helper/uni-app-types': ^1.0.0-alpha.6
  '@uni-helper/uni-ui-types': ^1.0.0-alpha.6
  '@uni-helper/uni-use': ^0.19.14
  '@uni-helper/unocss-preset-uni': ^0.2.11
  '@uni-helper/vite-plugin-uni-components': ^0.2.0
  '@uni-helper/vite-plugin-uni-layouts': ^0.1.10
  '@uni-helper/vite-plugin-uni-pages': ^0.2.28
  '@unocss/eslint-plugin': 66.0.0
  '@unocss/reset': 66.0.0
  '@vitejs/plugin-react': ^4.4.1
  '@vitejs/plugin-vue': ^5.2.4
  '@vitejs/plugin-vue-jsx': ^4.2.0
  '@vitest/browser': ^3.1.4
  '@vue/compiler-sfc': ^3.5.14
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': ^13.2.0
  ahooks: ^3.8.5
  bumpp: ^10.1.1
  c12: ^3.0.4
  cac: ^6.7.14
  conventional-changelog-cli: ^5.0.0
  defu: ^6.1.4
  eslint: ^9.27.0
  eslint-plugin-format: ^1.0.1
  extract-comments: ^1.1.0
  fast-glob: ^3.3.3
  find-up: ^7.0.0
  fs-extra: ^11.3.0
  lint-staged: ^16.0.0
  mlly: ^1.7.4
  pathe: ^2.0.3
  pinia: ^3.0.2
  pinia-plugin-persistedstate: ^4.3.0
  pkg-types: ^2.1.0
  playwright: ^1.52.0
  react: ^19.1.0
  react-dom: ^19.1.0
  react-router: ^7.6.0
  sass: ^1.89.0
  simple-git-hooks: ^2.13.0
  taze: ^19.1.0
  tsx: ^4.19.4
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: 66.0.0
  unocss-applet: ^0.10.0
  unplugin-auto-import: ^19.2.0
  unplugin-vue-components: 28.0.0
  unplugin-vue-router: ^0.12.0
  vite: ^6.3.5
  vite-plugin-checker: ^0.9.3
  vite-plugin-pages: ^0.33.0
  vite-plugin-vue-devtools: ^7.7.6
  vite-plugin-vue-layouts: ^0.11.0
  vitepress: ^1.6.3
  vitest: ^3.1.4
  vue: ^3.5.14
  vue-router: ^4.5.1
  vue-tsc: ^2.2.10
  yaml: ^2.8.0
  zustand: ^5.0.5
