packages:
  - packages/*
  - playground/*
  - docs

catalog:
  '@antfu/eslint-config': ^7.4.3
  '@commitlint/cli': ^20.4.2
  '@commitlint/config-conventional': ^20.4.2
  '@types/fs-extra': ^11.0.4
  '@types/node': ^24.10.9
  '@vixt/layer-shared': ^0.8.1
  bumpp: ^10.4.1
  c12: ^3.3.3
  cac: ^6.7.14
  citty: ^0.2.1
  conventional-changelog-cli: ^5.0.0
  defu: ^6.1.4
  eslint: ^9.39.2
  eslint-plugin-format: ^1.4.0
  execa: ^9.6.1
  extract-comments: ^1.1.0
  fast-glob: ^3.3.3
  find-up: ^8.0.0
  fs-extra: ^11.3.3
  jiti: ^2.6.1
  lint-staged: ^16.2.7
  magicast: ^0.5.2
  mlly: ^1.8.0
  pathe: ^2.0.3
  pkg-types: ^2.3.0
  rimraf: ^6.1.3
  sass: ^1.97.3
  simple-git-hooks: ^2.13.1
  taze: ^19.9.2
  tsdown: ^0.20.3
  typescript: ^5.9.3
  yaml: ^2.8.2

catalogs:
  nuxt:
    nuxt: ^4.3.1

  rolldown:
    vite: ^8.0.0-beta.15

  react:
    '@iconify/react': ^6.0.2
    '@reactuses/core': ^6.1.11
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
    ahooks: ^3.9.6
    react: ^19.2.4
    react-dom: ^19.2.4
    react-router: ^7.13.1
    zustand: ^5.0.11

  uni:
    '@dcloudio/types': ^3.4.28
    '@dcloudio/uni-app': 3.0.0-4080720251210001
    '@dcloudio/uni-app-plus': 3.0.0-4080720251210001
    '@dcloudio/uni-h5': 3.0.0-4080720251210001
    '@dcloudio/uni-mp-weixin': 3.0.0-4080720251210001
    '@dcloudio/uni-ui': ^1.5.11
    '@dcloudio/uni-uts-v1': 3.0.0-4080720251210001
    '@dcloudio/vite-plugin-uni': 3.0.0-4080720251210001
    '@uni-helper/uni-app-types': ^1.0.0-alpha.7
    '@uni-helper/uni-ui-types': ^1.0.0-alpha.7
    '@uni-helper/uni-use': ^0.19.17
    '@uni-helper/unocss-preset-uni': ^0.2.11
    '@uni-helper/vite-plugin-uni-components': ^0.2.10
    '@uni-helper/vite-plugin-uni-layouts': ^0.1.11
    '@uni-helper/vite-plugin-uni-pages': ^0.3.23
    unocss-applet: ^0.12.2

  vite:
    '@unocss/eslint-plugin': ^66.6.0
    '@unocss/reset': ^66.6.0
    '@vitejs/plugin-basic-ssl': ^2.1.4
    '@vitejs/plugin-legacy': ^8.0.0-beta.3
    '@vitejs/plugin-react': ^5.1.4
    '@vitejs/plugin-vue': ^6.0.4
    '@vitejs/plugin-vue-jsx': ^5.1.4
    '@vitest/browser': ^4.0.18
    '@vitest/browser-playwright': ^4.0.18
    playwright: ^1.58.2
    unocss: ^66.6.0
    unplugin-auto-import: ^21.0.0
    unplugin-vue-components: 28.0.0
    vite: ^7.3.1
    vite-bundle-analyzer: ^1.3.6
    vite-plugin-checker: ^0.12.0
    vite-plugin-pages: ^0.33.3
    vite-plugin-vue-devtools: ^8.0.6
    vite-plugin-vue-layouts: ^0.11.0
    vitepress: ^2.0.0-alpha.16
    vitest: ^4.0.18

  vue:
    '@iconify/vue': ^5.0.0
    '@vue/shared': ^3.5.29
    '@vue/tsconfig': ^0.8.1
    '@vueuse/core': ^13.9.0
    pinia: ^3.0.4
    pinia-plugin-persistedstate: ^4.7.1
    vue: ^3.5.29
    vue-router: ^5.0.3
    vue-tsc: ^3.2.5
