packages:
  - packages/*
  - playground/*
  - docs

catalog:
  '@antfu/eslint-config': ^5.3.0
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@dcloudio/types': ^3.4.19
  '@dcloudio/uni-app': 3.0.0-4070620250821001
  '@dcloudio/uni-app-plus': 3.0.0-4070620250821001
  '@dcloudio/uni-h5': 3.0.0-4070620250821001
  '@dcloudio/uni-mp-weixin': 3.0.0-4070620250821001
  '@dcloudio/uni-ui': ^1.5.11
  '@dcloudio/uni-uts-v1': 3.0.0-4070620250821001
  '@dcloudio/vite-plugin-uni': 3.0.0-4070620250821001
  '@iconify/react': ^6.0.1
  '@iconify/vue': ^5.0.0
  '@reactuses/core': ^6.0.6
  '@types/fs-extra': ^11.0.4
  '@types/react': ^19.1.12
  '@types/react-dom': ^19.1.9
  '@uni-helper/uni-app-types': ^1.0.0-alpha.6
  '@uni-helper/uni-ui-types': ^1.0.0-alpha.6
  '@uni-helper/uni-use': ^0.19.14
  '@uni-helper/unocss-preset-uni': ^0.2.11
  '@uni-helper/vite-plugin-uni-components': ^0.2.0
  '@uni-helper/vite-plugin-uni-layouts': ^0.1.11
  '@uni-helper/vite-plugin-uni-pages': ^0.3.9
  '@unocss/eslint-plugin': ^66.5.1
  '@unocss/reset': ^66.5.1
  '@vitejs/plugin-react': ^5.0.2
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.1.1
  '@vitest/browser': ^3.2.4
  '@vue/shared': ^3.5.21
  '@vue/tsconfig': ^0.8.1
  '@vueuse/core': ^13.9.0
  ahooks: ^3.9.5
  bumpp: ^10.2.3
  c12: ^3.2.0
  cac: ^6.7.14
  conventional-changelog-cli: ^5.0.0
  defu: ^6.1.4
  eslint: ^9.35.0
  eslint-plugin-format: ^1.0.1
  extract-comments: ^1.1.0
  fast-glob: ^3.3.3
  find-up: ^7.0.0
  fs-extra: ^11.3.1
  lint-staged: ^16.1.6
  mlly: ^1.8.0
  pathe: ^2.0.3
  pinia: ^3.0.3
  pinia-plugin-persistedstate: ^4.5.0
  pkg-types: ^2.3.0
  playwright: ^1.55.0
  react: ^19.1.1
  react-dom: ^19.1.1
  react-router: ^7.8.2
  sass: ^1.92.1
  simple-git-hooks: ^2.13.1
  taze: ^19.6.0
  tsx: ^4.20.5
  typescript: ^5.9.2
  unbuild: ^3.6.1
  unocss: ^66.5.1
  unocss-applet: ^0.11.0
  unplugin-auto-import: ^20.1.0
  unplugin-vue-components: 28.0.0
  unplugin-vue-router: ^0.15.0
  vite: ^7.1.5
  vite-plugin-checker: ^0.10.3
  vite-plugin-pages: ^0.33.1
  vite-plugin-vue-devtools: ^8.0.1
  vite-plugin-vue-layouts: ^0.11.0
  vitepress: ^1.6.4
  vitest: ^3.2.4
  vue: ^3.5.21
  vue-router: ^4.5.1
  vue-tsc: ^3.0.6
  yaml: ^2.8.1
  zustand: ^5.0.8
