packages:
  - packages/*
  - playground/*
  - docs
  - test
catalog:
  '@antfu/eslint-config': ^4.6.0
  '@commitlint/cli': ^19.7.1
  '@commitlint/config-conventional': ^19.7.1
  '@dcloudio/types': ^3.4.14
  '@dcloudio/uni-app': 3.0.0-alpha-4050320250224001
  '@dcloudio/uni-app-plus': 3.0.0-alpha-4050320250224001
  '@dcloudio/uni-h5': 3.0.0-alpha-4050320250224001
  '@dcloudio/uni-mp-weixin': 3.0.0-alpha-4050320250224001
  '@dcloudio/uni-ui': ^1.5.7
  '@dcloudio/vite-plugin-uni': 3.0.0-alpha-4050320250224001
  '@iconify/vue': ^4.3.0
  '@types/fs-extra': ^11.0.4
  '@uni-helper/uni-app-types': ^1.0.0-alpha.6
  '@uni-helper/uni-ui-types': ^1.0.0-alpha.6
  '@uni-helper/uni-use': ^0.19.14
  '@uni-helper/unocss-preset-uni': ^0.2.11
  '@uni-helper/vite-plugin-uni-components': ^0.2.0
  '@uni-helper/vite-plugin-uni-layouts': ^0.1.10
  '@uni-helper/vite-plugin-uni-pages': ^0.2.28
  '@unocss/eslint-plugin': ^66.0.0
  '@unocss/reset': ^66.0.0
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@vitest/browser': ^3.0.8
  '@vue/tsconfig': ^0.7.0
  '@vue/compiler-sfc': ^3.5.13
  '@vueuse/core': ^12.8.2
  bumpp: ^10.0.3
  c12: ^3.0.2
  cac: ^6.7.14
  conventional-changelog-cli: ^5.0.0
  defu: ^6.1.4
  eslint: ^9.21.0
  eslint-plugin-format: ^1.0.1
  find-up: ^7.0.0
  fs-extra: ^11.3.0
  lint-staged: ^15.4.3
  mlly: ^1.7.4
  pathe: ^2.0.3
  pinia: ^3.0.1
  pinia-plugin-persistedstate: ^4.2.0
  pkg-types: ^2.1.0
  playwright: ^1.51.0
  sass: ^1.85.1
  simple-git-hooks: ^2.11.1
  taze: ^18.6.0
  tsx: ^4.19.3
  typescript: ^5.8.2
  unbuild: ^3.5.0
  unocss: ^66.0.0
  unocss-applet: ^0.9.0
  unplugin-auto-import: ^19.1.1
  unplugin-vue-components: 28.0.0
  unplugin-vue-router: ^0.12.0
  uview-plus: ^3.3.74
  vite: ^6.2.1
  vite-plugin-checker: ^0.9.0
  vite-plugin-vue-devtools: ^7.7.2
  vite-plugin-vue-layouts: ^0.11.0
  vitepress: ^1.6.3
  vitest: ^3.0.8
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.8
