packages:
  - packages/*
  - playground/*
  - docs
  - test
catalog:
  '@antfu/eslint-config': ^4.1.1
  '@commitlint/cli': ^19.7.1
  '@commitlint/config-conventional': ^19.7.1
  '@dcloudio/types': ^3.4.14
  '@dcloudio/uni-app': 3.0.0-alpha-4050120250114001
  '@dcloudio/uni-app-plus': 3.0.0-alpha-4050120250114001
  '@dcloudio/uni-h5': 3.0.0-alpha-4050120250114001
  '@dcloudio/uni-mp-weixin': 3.0.0-alpha-4050120250114001
  '@dcloudio/uni-ui': ^1.5.7
  '@dcloudio/vite-plugin-uni': 3.0.0-alpha-4050120250114001
  '@iconify/vue': ^4.3.0
  '@types/fs-extra': ^11.0.4
  '@uni-helper/uni-app-types': ^1.0.0-alpha.6
  '@uni-helper/uni-ui-types': ^1.0.0-alpha.6
  '@uni-helper/uni-use': ^0.19.14
  '@uni-helper/unocss-preset-uni': ^0.2.11
  '@uni-helper/vite-plugin-uni-components': ^0.2.0
  '@uni-helper/vite-plugin-uni-layouts': ^0.1.10
  '@uni-helper/vite-plugin-uni-pages': ^0.2.28
  '@unocss/eslint-plugin': ^65.4.3
  '@unocss/reset': ^65.4.3
  '@vitejs/plugin-vue': ^5.2.0
  '@vitejs/plugin-vue-jsx': ^4.1.0
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': ^12.5.0
  bumpp: ^10.0.2
  c12: ^2.0.1
  cac: ^6.7.14
  conventional-changelog-cli: ^5.0.0
  defu: ^6.1.4
  eslint: ^9.19.0
  eslint-plugin-format: ^1.0.1
  find-up: ^7.0.0
  fs-extra: ^11.3.0
  lint-staged: ^15.4.3
  mlly: ^1.7.4
  pathe: ^2.0.2
  pinia: ^2.3.1
  pinia-plugin-persistedstate: ^4.2.0
  pkg-types: ^1.3.1
  sass: ^1.84.0
  simple-git-hooks: ^2.11.1
  taze: ^18.4.0
  tsx: ^4.19.2
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unocss: ^65.4.3
  unocss-applet: ^0.9.0
  unplugin-auto-import: ^19.0.0
  unplugin-vue-components: ^28.0.0
  unplugin-vue-router: ^0.11.2
  uview-plus: ^3.3.65
  vite: ^6.1.0
  vite-plugin-checker: ^0.8.0
  vite-plugin-vue-devtools: ^7.7.1
  vite-plugin-vue-layouts: ^0.11.0
  vitepress: ^1.6.3
  vitest: ^3.0.5
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.0
