name: Deploy To gh-pages

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 'lts'
          cache: true

      - name: Build Docs
        run: vpr build:docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: docs/.vitepress/dist
